### ISSUE TITLE
如何能够及时追踪原项目与当前项目的不同，并知道要翻译哪些部分

### ISSUE THREAD

**Issue by Prodesire** [Prodesire/Python-Guide-CN#25]
本翻译项目实际上是在GitHub上新建的项目，而不是fork自Python-Guide，这是为了对这个翻译项目有更好的自由度。但即便是是fork过来的项目，也会有这样的问题。就是当我们翻译完某一部分后，原英文项目的对应部分进行了增删，这时我们并不知道它进行了修改，也很难知道它修改了哪些部分，我们就不能及时更新翻译，这样很难保证这个翻译项目是最新的内容。
请问大家有什么好的解决方案呢？欢迎踊跃讨论~

**Comment by liuliqiang** [comment]
我浏览了一下，发现原项目的更新频率也不快
不知道每周或者每月对原项目进行一次 diff，
然后更新一波，顺便还能来一个 weekly 或者 monthly 邮件
不知道觉得怎样？

**Comment by Prodesire** [comment]
比较不好解决的就是diff，我们这边已经完全是中文了，很难和原来的英文做diff。

**Comment by liuliqiang** [comment]
不用英文和中文做diff
我们中文要和英文的某一commit做基准翻译
当英文的更新后，以英文的对应 commit 为基准diff
那我们中文需要翻译的部分就只是这部分英文diff 的结果了

**Comment by Prodesire** [comment]
是个不错的想法，接下来可以试行一下~

**Comment by n7then** [comment]
去看了下英文项目,更新了不少.

**Comment by Prodesire** [comment]
恩，准备开始更新了。
