### ISSUE TITLE
/writing/structure中翻译失误

### ISSUE THREAD

**Issue by xent9312** [Prodesire/Python-Guide-CN#27]
> Python中更可能出现馄饨代码：这类代码包含上百段相似的逻辑碎片，通常是缺乏 合适结构的类或对象，如果你始终弄不清手头上的任务应该使用FurnitureTable， AssetTable还是Table，甚至TableNew，也许你已经陷入了馄饨代码中

raise Exception("馄饨 -> 混沌")

有没有饺子代码，在线等挺急的

**Comment by Prodesire** [comment]
那就看接下来有没有小伙伴给你提供咯。问题已修正哈~
