### ISSUE TITLE
希望可以上线Gitbook

### ISSUE THREAD

**Issue by tangjyan** [Prodesire/Python-Guide-CN#32]
希望可以上线Gitbook，gitbook有很好的阅读体验。

**Comment by Prodesire** [comment]
gitbook只支持markdown，restructedtext转换成markdown要做大量工作，所以暂无支持计划。
如果其他伙伴有意向支持，可以提交PR。

**Comment by Prodesire** [comment]
该issue近两月没有童靴响应，关闭之~
