### ISSUE TITLE
首页引言译者注修改建议

### ISSUE THREAD

**Issue by chaozh** [Prodesire/Python-Guide-CN#34]
首页对“确保您的毛巾在哪”理解有误，towel 浴巾的梗出自著名科幻小说《银河系漫游指南》，按照书中设定进行星际旅行最重要的是确保拥有浴巾。原文如下：
> A towel, it says, is about the most massively useful thing an interstellar hitchhiker can have. Partly it has great practical value - you can wrap it around you for warmth as you bound across the cold moons of Jaglan Beta; you can lie on it on the brilliant marble-sanded beaches of Santraginus V, inhaling the heady sea vapours; you can sleep under it beneath the stars which shine so redly on the desert world of Kakrafoon; use it to sail a mini raft down the slow heavy river Moth; wet it for use in hand-to- hand-combat; wrap it round your head to ward off noxious fumes or to avoid the gaze of the Ravenous Bugblatter Beast of Traal (a mindboggingly stupid animal, it assumes that if you can't see it, it can't see you - daft as a bush, but very ravenous); you can wave your towel in emergencies as a distress signal, and of course dry yourself off with it if it still seems to be clean enough. More importantly, a towel has immense psychological value. For some reason, if a strag (strag: non-hitch hiker) discovers that a hitch hiker has his towel with him, he will automatically assume that he is also in possession of a toothbrush, face flannel, soap, tin of biscuits, flask, compass, map, ball of string, gnat spray, wet weather gear, space suit etc., etc. Furthermore, the strag will then happily lend the hitch hiker any of these or a dozen other items that the hitch hiker might accidentally have "lost". What the strag will think is that any man who can hitch the length and breadth of the galaxy, rough it, slum it, struggle against terrible odds, win through, and still knows where his towel is is clearly a man to be reckoned with.

作者用这个著名的梗是想表明就要开始惊心动魄的“星际旅行”啦，因此这个译者注建议修改

> （译者注：洗澡需要浴巾，大概是说先准备好环境）

**Comment by Prodesire** [comment]
感谢指出疏漏，以及引用。
看了引用，作者的意思应该还是要先准备好环境，环境及对于开发者的重要性如浴巾对于星际旅行的重要性。
那么可否改成这样？
> 但首先，让我们确保您拥有浴巾。（译者注：towel 浴巾的梗引自著名科幻小说《银河系漫游指南》，大概是说先准备好环境）

**Comment by Prodesire** [comment]
@chaozh 方便给出原文的引用吗？

**Comment by wenliang** [comment]
哈哈, 我正想要说这个梗, 发现已经有了.

本文的名字是"The hitchhiker's guide to python"
就是向 "The hitchhiker's guide to galaxy" 致敬.

个人建议: 
> 但首先，让我们确保您拥有这次旅行需要的"浴巾"。（译者注：towel 浴巾的梗引自著名科幻小说《银河系漫游指南》，大概是说先准备好不起眼但很重要的东西）

**Comment by Prodesire** [comment]
"先准备好不起眼但很重要的东西"，这里需要明确。结合语境，我觉得指开发环境。

**Comment by wenliang** [comment]
:wink:  都可以.

> 但首先，让我们确保您拥有这次旅行需要的"浴巾"。（译者注：towel 浴巾的梗引自著名科幻小说《银河系漫游指南》，大概是说先准备好不起眼但很重要的东西,  例如浴巾之于《银河系漫游指南》, 开发环境之于本文 《python 漫游指南》）

好像有点啰嗦 :sweat:

**Comment by chaozh** [comment]
推荐至少把同名电影看啦，就能理解这个梗啦。个人感觉跟开发环境没啥联系，这个梗本身就是无厘头的，这里算引用一个常用梗。挺经典有趣的科幻电影，非常搞笑。

**Comment by Prodesire** [comment]
感谢两位，已更新~
