### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by ListenLove** [Prodesire/Python-Guide-CN#49]
地址： https://pythonguidecn.readthedocs.io/zh/latest/dev/virtualenvs.html#id3

> ~ 会扩展为您的家目录的局对路径

中的**局对路径**->**绝对路径**

> 局对路径->绝对路径

**Comment by Prodesire** [comment]
感谢！你能提个MR吗？

**Comment by ListenLove** [comment]
MR是什么意思。。。:flushed:

**Comment by Prodesire** [comment]
Merge Request， 合并请求
